CarRent/Controllers/RentController.cs
using CarRent.DAL;
using CarRent.Models.Rent;
using CarRent.Service;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CarRent.Controllers;

[Authorize(Roles = "User,Employee,Administrator")]
public class RentController : Controller
{
    private readonly IRentService _rentService;
    private readonly IVehicleService _vehicleService;
    private readonly UserManager<User> _userManager;

	public RentController(IRentService rentService, IVehicleService vehicleService, UserManager<User> userManager)
    {
        _rentService = rentService;
        _vehicleService = vehicleService;
        _userManager = userManager;
	}

    [HttpGet]
    public async Task<IActionResult> AllActiveRents()
    {
        var model = new List<RentViewModel>();
        var rents = await _rentService.GetAll();

        foreach (var rent in rents)
		{
            var rentViewModel = new RentViewModel()
            {
                RentId = rent.Id,
                BookingDateTime = rent.BookingDateTime,
                PlannedDateOfReceipt = rent.PlannedDateOfReceipt,
                DateOfReceipt = rent.DateOfReceipt,
                DateOfReturn = rent.DateOfReturn,
                Description = rent.Description,
                RentPeriod = rent.RentPeriod,
                Receipt = rent.Receipt,
                RentedVehicle = await _vehicleService.GetById(rent.VehicleId),
                RentUser = await _userManager.FindByIdAsync(rent.UserId)
            };

            model.Add(rentViewModel);
		}
        
        return View(model);  
    }

    [HttpGet]
    public async Task<IActionResult> RentVehicle(Guid rentId)
	{
        var rentToUpdate = await _rentService.GetById(rentId);
        if (rentToUpdate != null)
		{
            rentToUpdate.DateOfReceipt = DateTime.Now;  
            await _rentService.Update(rentToUpdate);

        }
        return RedirectToAction("AllActiveRents");
	}

    [HttpGet]
    public async Task<IActionResult> ReturnVehicle(Guid rentId)
    {
        var rentToUpdate = await _rentService.GetById(rentId);

        if (rentToUpdate != null)
        {
            rentToUpdate.DateOfReturn = DateTime.Now;
            await _rentService.Update(rentToUpdate);

            var selectedVehicle = await _vehicleService.GetById(rentToUpdate.VehicleId);

            selectedVehicle.Available = true;
            await _vehicleService.Update(selectedVehicle);
        }

        return RedirectToAction("AllActiveRents");
    }

    [HttpGet]
    public IActionResult AddRentView(Guid vehicleid)
    {
        return View(new Rent{VehicleId = vehicleid });
    }

    [HttpGet]
    public async Task<IActionResult> MyRents(string userId)
    {
        var model = new List<RentViewModel>();
        var rents = await _rentService.GetAll();
        var userRents = rents.Where(x => x.UserId == userId);

        foreach (var rent in userRents)
        {
            var rentViewModel = new RentViewModel()
            {
                RentId = rent.Id,
                BookingDateTime = rent.BookingDateTime,
                PlannedDateOfReceipt = rent.PlannedDateOfReceipt,
                DateOfReceipt = rent.DateOfReceipt,
                DateOfReturn = rent.DateOfReturn,
                Description = rent.Description,
                RentPeriod = rent.RentPeriod,
                Receipt = rent.Receipt,
                RentedVehicle = await _vehicleService.GetById(rent.VehicleId),
                RentUser = await _userManager.FindByIdAsync(rent.UserId)
            };

            model.Add(rentViewModel);
        }

        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> PostRent(Rent rent)
    {
        var selectedVehicle = await _vehicleService.GetById(rent.VehicleId);

        selectedVehicle.Available = false;
        await _vehicleService.Update(selectedVehicle);

        rent.BookingDateTime = DateTime.Now;
        rent.Receipt = selectedVehicle.PricePerDay * rent.RentPeriod;
        rent.UserId = _userManager.GetUserId(this.User); 
        
        await _rentService.Add(rent);
        return RedirectToAction("MyRents", new { userId = rent.UserId });
    }
}

CarRent/Controllers/VehicleController.cs
using CarRent.DAL;
using CarRent.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CarRent.Controllers
{
    [Authorize]
    public class VehicleController : Controller
    {
        private readonly ILogger<VehicleController> _logger;
        private readonly IVehicleService _vehicleService;

        public VehicleController(ILogger<VehicleController> logger, IVehicleService vehicleService)
        {
            _logger = logger;
            _vehicleService = vehicleService;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var result = await _vehicleService.GetAll();
            return View(result);
        }

        [HttpGet]
        [Authorize(Roles = "Employee")]
        public IActionResult AddVehicleView()
        {
            return View(new Vehicle());
        } 
        
        [HttpPost]
        [Authorize(Roles = "Employee")]
        public async Task<IActionResult> PostVehicle(Vehicle vehicle)
        {
            //Set other initial model fields 
            vehicle.Image = new byte[] {0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1};
            vehicle.Available = true;

            await _vehicleService.Add(vehicle);
            return RedirectToAction("Index");
        }
    }
}

CarRent/Views/Shared/_Layout.cshtml
@using CarRent.Common
@using CarRent.DAL
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - CarRent</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/bootstrap.css/bootstrap.min.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/CarRent.styles.css" asp-append-version="true"/>

</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CarRent</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>

                    @if(User.Identity.IsAuthenticated && User.IsInRole(RoleType.Employee.ToString()))
                       {
                        <li class="nav-item" >
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vehicle" asp-action="AddVehicleView">Add new car</a>
                        </li>
                        <li class="nav-item" >
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rent" asp-action="AllActiveRents">Active rents</a>
                        </li>
                        }

                    @if(User.Identity.IsAuthenticated && User.IsInRole(RoleType.User.ToString()))
                        {
                          <li class="nav-item" >
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rent" asp-action="MyRents" asp-route-userid="@UserManager.GetUserId(User)">My rents</a>
                           </li>                          
                        }

                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Vehicle" asp-action="Index">Explore</a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - CarRent - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/js/Common.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>